<a href="https://colab.research.google.com/github/nattanan13/-nattanan/blob/main/Q14%2C15%2C16_640631119_Nattanan_Prompanya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Q14:Try this

In [1]:
import numpy as np
from scipy.linalg import solve
A = np.array([[1., 2.], [3., 4.]])
b = np.array([1., 4.])
x = solve(A,b)

In [2]:
print(x)

[ 2.  -0.5]


Q15: Create a Matrix X(4x3)

In [3]:

X = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(X)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]



Q16: Create Matrix Aij

In [6]:
#matrix(m,n)
#m = row
#n = column
#i  in m
#j in n
#3 case

c = []

def matrix(m,n):
  for i in range(m) :
    b = []
    for j in range(n) :
      if i<j and j!=m :
        a = 0
      elif i==j or j==m :
        a = 1
      else:
        a = -1
      b.append(a)   
    c.append(b)

  print(np.array(c))


matrix(5,5)

[[ 1  0  0  0  0]
 [-1  1  0  0  0]
 [-1 -1  1  0  0]
 [-1 -1 -1  1  0]
 [-1 -1 -1 -1  1]]
